name: cna2gex
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - r
dependencies:
  - black=19.10b0
  - gdown=4.5.3
  - ipython=8.3.0
  - numpy=1.22.3
  - pandas=1.4.2
  - pip=22.3.1
  - pytorch=1.13.0
  - rpy2=3.5.1
  - scikit-learn=1.0.2
  - selenium=3.141.0
  - tqdm=4.64.0
  - webdriver-manager=3.8.4
  - pip:
    - torchsummary==1.5.1
